CREATE TABLE IF NOT EXISTS singer (
	id SERIAL PRIMARY KEY,
	pseudonim VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS genre (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS album (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	album_year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS singer_genres (
	id SERIAL PRIMARY KEY,
	singer_id INTEGER NOT NULL REFERENCES singer(id),
	genre_id INTEGER NOT NULL REFERENCES genre(id)
);

CREATE TABLE IF NOT EXISTS album_singer (
	id SERIAL PRIMARY KEY,
	singer_id INTEGER NOT NULL REFERENCES singer(id),
	album_id INTEGER NOT NULL REFERENCES album(id)
);

CREATE TABLE IF NOT EXISTS track (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	duration INTEGER NOT NULL,
	album_id INTEGER NOT NULL REFERENCES album(id)
);

CREATE TABLE IF NOT EXISTS collection (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	collection_year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS track_collection (
	id SERIAL PRIMARY KEY,
	track_id INTEGER NOT NULL REFERENCES track(id),
	collection_id INTEGER NOT NULL REFERENCES collection(id)
);